name: Publish Docker Image

on:
  push:
    branches:
      - main      
  workflow_dispatch:
  
jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Commit Hash
        id: get_commit_hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get Version
        id: get_version
        run: echo "version=$(cat ci/version)" >> $GITHUB_ENV

      - name: Get Build Number
        id: get_build_number
        run: echo "build_number=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Debug - Print Variables
        run: |
          echo "Version: ${{ env.version }}"
          echo "Build Number: ${{ env.build_number }}"
          echo "Commit Hash: ${{ env.commit_hash }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .                
          file: ci/Dockerfile  
          push: true 
          tags: |
            raphaeleze/recipex:${{ env.version }}
            raphaeleze/recipex:${{ env.version }}-${{ env.build_number }}
            raphaeleze/recipex:${{ env.version }}-${{ env.build_number }}-${{ env.commit_hash }}
