name: Publish Image To AWS ECR

on: 
  workflow_dispatch:

env:
  ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: "us-west-2"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPO_NAME: recipex-springboot-app # we have to create this using terraform first in recipeX-aws-tf-infra repo

jobs:
  docker_build: 
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Commit Hash
        id: get_commit_hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get Version
        id: get_version
        run: echo "version=$(cat ci/version)" >> $GITHUB_ENV

      - name: Get Build Number
        id: get_build_number
        run: echo "build_number=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Debug - Print Variables
        run: |
          echo "Version: ${{ env.version }}"
          echo "Build Number: ${{ env.build_number }}"
          echo "Commit Hash: ${{ env.commit_hash }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authenticate Docker to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t recipex:${{ env.version }} -f ci/Dockerfile .

      - name: Tag Docker Image for ECR
        run: |
          IMAGE_TAG="${{ env.version }}-${{ env.build_number }}-${{ env.commit_hash }}"
          docker tag recipex:${{ env.version }} ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:$IMAGE_TAG

      - name: Push Docker Image to ECR
        run: |
          IMAGE_TAG="${{ env.version }}-${{ env.build_number }}-${{ env.commit_hash }}"
          docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:$IMAGE_TAG
